Naamgeving regels
Logius-standaarden/API-mod-transport-security pull request #1
Opened 2024-05-27 07:06 UTC by sanderke

2024-05-27 08:19 UTC, joostfarla requested changes

2024-05-27 08:19 UTC, joostfarla commented on transport-security.md
> +  <p class="rulelab"><strong>/transport/TLS</strong>: Secure connections using TLS</p>
De standaard voor rule-IDs is `kebab-case`. Deze zouden dus altijd lowercase moeten zijn.

2024-05-27 11:53 UTC, joostfarla approved these changes

2024-06-06 06:55 UTC, mrtn78 approved these changes

2024-06-06 06:57 UTC, merged